### ISSUE TITLE
Error message when running script and pressing Escape to exit

### ISSUE THREAD

**Issue by AzP** [Sebastiaan76/waybar_wireplumber_audio_changer#1] opened 2023-07-06 17:09 UTC
I've tried using this script but it doesn't seem to work correctly for me.

I've tried running it from the terminal to debug it and this is the output I get:

```
Traceback (most recent call last):
  File ".config/waybar/modules/audio_changer.py", line 50, in <module>
    selected_sink_name = subprocess.check_output(f"echo '{output}' | wofi --show=dmenu --hide-scroll --allow-markup --define=hide_search=true --location=top_right --width=600 --height=200 --xoffset=-60", shell=True, encoding='utf-8').strip()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo '<b>-> Starship/Matisse HD Audio Controller Analog Stereo - Default</b>
' | wofi --show=dmenu --hide-scroll --allow-markup --define=hide_search=true --location=top_right --width=600 --height=200 --xoffset=-60' returned non-zero exit status 1.
```

The list of devices that I get only has one entry, and I'm nothing happens when I click the entry, so I have to exit by pressing the Escape key. Then the error pops up in the terminal.

**Comment by Sebastiaan76** [comment] 2023-07-06 18:16
Any chance you could paste the output of ```wpctl status```?

**Comment by AzP** [comment] 2023-07-06 18:34
Sure, here goes:

```
PipeWire 'pipewire-0' [0.3.72, peter@skare, cookie:2085161294]
 └─ Clients:
        31. WirePlumber                         [0.3.72, peter@skare, pid:2446]
        32. WirePlumber [export]                [0.3.72, peter@skare, pid:2446]
        56. pipewire                            [0.3.72, peter@skare, pid:3032]
        57. spotify                             [0.3.72, peter@skare, pid:2606]
        59. xdg-desktop-portal-wlr              [0.3.72, peter@skare, pid:4328]
        60. xdg-desktop-portal                  [0.3.72, peter@skare, pid:2635]
        61. Steam Voice Settings                [0.3.72, peter@skare, pid:4849]
        62. Steam                               [0.3.72, peter@skare, pid:4849]
        63. Chromium input                      [0.3.72, peter@skare, pid:7438]
        64. libcanberra                         [0.3.72, peter@skare, pid:2602]
        70. Firefox                             [0.3.72, peter@skare, pid:2604]
        71. Chromium input                      [0.3.72, peter@skare, pid:284130]
        73. Skype                               [0.3.72, peter@skare, pid:284563]
        74. spotify                             [0.3.72, peter@skare, pid:2606]
        75. Chromium input                      [0.3.72, peter@skare, pid:286561]
        76. spotify                             [0.3.72, peter@skare, pid:2606]
        81. Firefox                             [0.3.72, peter@skare, pid:2604]
        82. spotify                             [0.3.72, peter@skare, pid:2606]
        99. libcanberra                         [0.3.72, peter@skare, pid:284251]
       101. spotify                             [0.3.72, peter@skare, pid:2606]
       102. spotify                             [0.3.72, peter@skare, pid:2606]
       116. spotify                             [0.3.72, peter@skare, pid:2606]
       134. libcanberra                         [0.3.72, peter@skare, pid:919018]
       138. waybar                              [0.3.72, peter@skare, pid:964305]
       139. libcanberra                         [0.3.72, peter@skare, pid:836392]
       141. libcanberra                         [0.3.72, peter@skare, pid:771888]
       148. wpctl                               [0.3.72, peter@skare, pid:974293]
       149. Lollypop                            [0.3.72, peter@skare, pid:436235]

Audio
 ├─ Devices:
 │      40. Navi 21/23 HDMI/DP Audio Controller [alsa]
 │      41. C920 HD Pro Webcam                  [alsa]
 │      42. Starship/Matisse HD Audio Controller [alsa]
 │  
 ├─ Sinks:
 │  *   46. Starship/Matisse HD Audio Controller Analog Stereo [vol: 0.57]
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │      45. C920 HD Pro Webcam Analog Stereo    [vol: 1.00]
 │  *   47. Starship/Matisse HD Audio Controller Analog Stereo [vol: 1.00]
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:
        65. spotify                                                     
             68. output_FR       > ALC1220 Analog:playback_FR	[init]
             69. output_FL       > ALC1220 Analog:playback_FL	[init]
        77. Skype                                                       
             85. output_FL       > ALC1220 Analog:playback_FL	[init]
             86. output_FR       > ALC1220 Analog:playback_FR	[init]
        79. spotify                                                     
             93. output_FR       > ALC1220 Analog:playback_FR	[init]
            100. output_FL       > ALC1220 Analog:playback_FL	[init]
        84. Skype                                                       
             87. input_FL        < ALC1220 Analog:capture_FL	[init]
             88. monitor_FL     
             89. input_FR        < ALC1220 Analog:capture_FR	[init]
             90. monitor_FR     
       103. spotify                                                     
             94. output_FR       > ALC1220 Analog:playback_FR	[init]
             95. output_FL       > ALC1220 Analog:playback_FL	[init]
       127. Lollypop                                                    
            126. output_FR       > ALC1220 Analog:playback_FR	[init]
            140. output_FL       > ALC1220 Analog:playback_FL	[init]
       128. spotify                                                     
            142. output_FL       > ALC1220 Analog:playback_FL	[active]
            152. output_FR       > ALC1220 Analog:playback_FR	[active]

Video
 ├─ Devices:
 │      38. HD Pro Webcam C920                  [v4l2]
 │      39. HD Pro Webcam C920                  [v4l2]
 │  
 ├─ Sinks:
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  *   43. HD Pro Webcam C920 (V4L2)          
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Settings
 └─ Default Configured Node Names:
         0. Audio/Sink    alsa_output.pci-0000_0d_00.4.analog-stereo
         1. Audio/Source  alsa_input.pci-0000_0d_00.4.analog-stereo
```

**Comment by Sebastiaan76** [comment] 2023-07-06 22:16
The error message isn't a big deal ( but I'll handle the case where a user doesn't select anything by pressing ESC a bit more gracefully ).

You only have one Audio Sink ```46. Starship/Matisse HD Audio Controller Analog Stereo [vol: 0.57]```. So there's not really anything else to select. 

You can either click on that, or press enter to select it ( or any other available Sink ). Or, ESC out of the dialog (which is just Wofi launcher in dmenu mode ).

Was it just the error message that was the issue, or were you expecting a different behaviour?

**Comment by Sebastiaan76** [comment] 2023-07-06 22:26
I've fixed the error message. But  I can't help with anything else for the time being, as the script is functioning as intended.

**Comment by AzP** [comment] 2023-07-06 22:41
Thanks for looking into it, it was the error message that I was reacting to.

I only have one sink, but two ports, which seems to be a pretty common case
for these on-board sound cards. I've tried to split it up in
pipewire/wireplumber so it's possible to toggle between them but haven't
gotten it working yet. I do however see both ports in pavucontrol, but
switching between them doesn't work (one just makes it go quiet) so there's
something wrong with my settings.
But that's got nothing to do with your module and script, so I digress!
Thanks for the good work!

Den fre 7 juli 2023 00:26Sebastiaan Stoffels ***@***.***>
skrev:

**Comment by Sebastiaan76** [comment] 2023-07-06 22:52
If you can get it to split out and show up as a separate Audio Sink, then the script should be able to toggle it no problem. 
Good luck. Will close this off as resolved for now.

cheers
Seb

**Closed as completed by Sebastiaan76** 2023-07-06 22:52 UTC

**Comment by AzP** [comment] 2023-07-07 09:56
Just for future reference, it's great to link/mention bugs in the commits! For instance the commit #e57d6b0 when closing the bug. But I just noticed that it's only possible to mention Pull Requests or issues from bugs.

But of course that's up to the developer/maintainer of the project.
